# Generated by Django 2.2.6 on 2019-10-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='prode',
            name='participantes',
            field=models.ManyToManyField(to='prodes.Participante'),
        ),
    ]
