# Generated by Django 2.2.6 on 2019-10-01 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodes', '0002_auto_20191001_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prode',
            name='participantes',
        ),
    ]
