# Generated by Django 2.2.6 on 2019-10-02 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prodes', '0005_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=120)),
                ('visitante', models.CharField(max_length=120)),
                ('resultado', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodes.Fecha')),
            ],
        ),
    ]
