# Generated by Django 2.2.6 on 2019-10-03 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prodes', '0006_partido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pronostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodes.Participante')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodes.Partido')),
            ],
        ),
    ]
